Utor/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

main/urls.py
from django.urls import include, path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
	path("", views.index, name="index"),
	path("login/", views.login, name="login"),
	path("login/<int:new_user>/", views.login, name="login_new_user"),
	path("logout/", views.logout, name="logout"),
	path("create_account/", views.create_account, name="create_account"),
	path("verify_account/<str:email_key>/", views.verify_account, name="verify_account"),
	path("profile/<int:user_id>/", views.profile_by_id, name="profile_by_id"),
	path("profile/<str:username>/", views.profile, name="profile"),
	path("tutor_profile/<str:tutor>/", views.tutor_profile, name='tutor_profile'),
	path('tutor_search/', views.tutor_search, name='tutor_search'),
	path('create_message_group/<str:username>/', views.create_message_group, name='create_message_group'),
    path('review_page/<str:tutor>/', views.review_page, name="review_page"),
    path('reviews/<str:username>/', views.user_reviews, name='user_reviews'),
	path('message_page/', views.message_page, name='message_page'),
	path('send_message/<str:dmid>/', views.send_message, name='send_message'),
	path('enable_tutoring/<str:username>/', views.enable_tutoring, name='enable_tutoring'),
	path("groups/", views.study_groups, name="study_groups"),
	path("groups/create_study_group/", views.create_study_group, name="create_study_group"),
	path("groups/view_group/<int:group_id>/", views.view_group, name="view_group"),
	path("groups/view_group/<int:group_id>/make_post/", views.make_post, name="make_post"),
	path("groups/view_group/<int:group_id>/group_chat/", views.group_chat, name="group_chat"),
	path("groups/view_group/<int:group_id>/schedule/", views.schedule, name="schedule"),
	path("groups/view_group/<int:group_id>/schedule/<str:past>/", views.schedule, name="schedule_past"),
	path("notifications/", views.notifications, name="notifications"),
	path("join_group/<int:group_id>/", views.join_group, name="join_group"),
	path('ajax/setOverall/<str:tutor>/', views.setOverall, name="setOverall"),
	path('ajax/setEffective/<str:tutor>/', views.setEffective, name="setEffective"),
	path('ajax/setTime/<str:tutor>/', views.setTime, name="setTime"),
 	path('ajax/setPatience/<str:tutor>/', views.setPatience, name="setPatience"),
	path('ajax/setKnowledge/<str:tutor>/', views.setKnowledge, name="setKnowledge"),
	path("ajax/save_desc/<int:group_id>/", views.save_desc, name="save_desc"),
	path("ajax/save_bio/<str:username>/", views.save_bio, name="save_bio"),
	path("ajax/save_zip/<str:username>/", views.save_zip, name="save_zip"),
	path("ajax/save_pay/<str:username>/", views.save_pay, name="save_pay"),
 	path("ajax/add_subject/<str:username>/", views.add_subject, name="add_subject"),
	path("ajax/remove_subject/<str:username>/", views.remove_subject, name="remove_subject"),
	path("ajax/add_tutoring/<str:username>/", views.add_tutoring, name="add_tutoring"),
	path("ajax/remove_tutoring/<str:username>/", views.remove_tutoring, name="remove_tutoring"),
	path("ajax/delete_notification/<int:notification_id>/", views.delete_notification, name="delete_notification"),
	path("ajax/request_join/<int:group_id>/", views.request_join, name="request_join"),
	path("ajax/accept_request/<int:group_id>/<int:user_id>/", views.accept_request, name="accept_request"),
	path("ajax/reject_request/<int:group_id>/<int:user_id>/", views.reject_request, name="reject_request"),
	path("ajax/leave_group/<int:group_id>/", views.leave_group, name="leave_group"),
	path("ajax/kick_user/", views.kick_user, name="kick_user"),
	path("ajax/invite/", views.invite, name="invite"),
	path("ajax/make_comment/", views.make_comment, name="make_comment"),
	path("ajax/schedule/", views.make_schedule_item, name="make_schedule_item"),
	path("ajax/remove_meeting/<int:meeting_id>/", views.remove_meeting, name="remove_meeting"),
	path("ajax/delete_group/", views.delete_group, name="delete_group"),
	re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
import json
import datetime
import pytz

class University(models.Model):
    name = models.CharField(max_length=150)
    domains = models.TextField(null=True)
    web_pages = models.TextField(null=True)
    country = models.CharField(max_length=50)
    alpha_two_code = models.CharField(max_length=10, null=True)
    state_province = models.CharField(max_length=100,null=True)

    def get_domains(self):
        return json.loads(self.domains or "[]")

    def get_webpages(self):
        return json.loads(self.web_pages or "[]")

    @staticmethod
    def get_valid_domains():
        with open("main/static/main/valid_domains.txt") as vd:
            ret = eval(vd.read())
        return ret

class User(AbstractUser):
    tutor_subjects = models.TextField(null=True)
    student_subjects = models.TextField(null=True)
    university = models.ForeignKey(University, on_delete=models.PROTECT, null=True, blank=True)
    bio = models.TextField(default="This user hasn't set their bio")
    is_verified = models.BooleanField(default=False)
    email_key = models.CharField(max_length=50, unique=True)
    tutoring_enabled = models.BooleanField(default=False)
    tutoring_pay = models.DecimalField(null=True, decimal_places=2, max_digits=4, default=0.00)
    average_rating = models.DecimalField(null=True, decimal_places=2, max_digits=3, default=0.00)
    zip_code = models.IntegerField(null=True, default=28607)

    def get_tutor_subjects(self):
        return json.loads(self.tutor_subjects or "[]")
    def set_tutor_subjects(self, subjects):
        self.tutor_subjects = json.dumps(subjects)
        self.save()
    def add_tutor_subject(self, *subs):
        current = self.get_tutor_subjects()
        for x in subs:
            if x not in current:
                current.append(x)
        self.set_tutor_subjects(current)
    def remove_tutor_subject(self, *subs):
        current = self.get_tutor_subjects()
        for x in subs:
            try:
                current.remove(x)
            except ValueError:
                pass
        self.set_tutor_subjects(current)

    def get_student_subjects(self):
        return json.loads(self.student_subjects or "[]")
    def set_student_subjects(self, subjects):
        self.student_subjects = json.dumps(subjects)
        self.save()
    def add_student_subject(self, *subs):
        current = self.get_student_subjects()
        for x in subs:
            if x not in current:
                current.append(x)
        self.set_student_subjects(current)
    def remove_student_subject(self, *subs):
        current = self.get_student_subjects()
        for x in subs:
            try:
                current.remove(x)
            except ValueError:
                pass
        self.set_student_subjects(current)

    def has_notifications(self):
        return bool(Notification.objects.filter(user=self))

    def num_notifications(self):
        return len(Notification.objects.filter(user=self))

class StudyGroup(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owned_studygroups")
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    user_list = models.ManyToManyField(User)
    requests = models.ManyToManyField(User, related_name="requests_set")
    invitations = models.ManyToManyField(User, related_name="invitations_set")
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    course = models.CharField(max_length=10, null=True, blank=True)



class GroupPost(models.Model):
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length = 130)
    text = models.TextField(null=True, blank=True)
    image_source = models.CharField(max_length=1000, null=True, blank=True)
    def get_ordered_comments(self):
        return self.comment_set.order_by("time")


class Recipient_Group(models.Model):
    dmid = models.CharField(max_length=100, unique=True)
    student = models.CharField(max_length=100, default="")
    tutor = models.CharField(max_length=100, default="")
    
    def all_messages(self):
        return Message.objects.filter(dmid=self.dmid).order_by("time")

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(GroupPost, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

class Conversation(models.Model):
    conversation_type = models.CharField(max_length=2, choices={"TM": "Tutor Message", "DM": "Direct Message", "GM": "Group Message"})
    users = models.ManyToManyField(User)

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    dmid = models.CharField(max_length=100)
    time = models.DateTimeField(auto_now_add=True)
    message = models.TextField()


class Notification(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    n_type = models.CharField(max_length=10)
    title = models.CharField(max_length = 150)
    text = models.CharField(max_length = 500)
    regarding_group = models.ForeignKey(StudyGroup, null=True, on_delete=models.CASCADE, related_name="gnot_set")
    regarding_user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name="regu_set")
    regarding_post = models.ForeignKey(GroupPost, null=True, on_delete=models.CASCADE, related_name="regp_set")
    regarding_dm = models.CharField(max_length=100, default="")

class CurrentGroupChatUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE)

    @staticmethod
    def create(user, group):
        q = CurrentGroupChatUser.objects.filter(user=user, group=group)
        if q.exists():
            return
        newcgu = CurrentGroupChatUser()
        newcgu.user = user
        newcgu.group = group
        newcgu.save()
        
class CurrentDMUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dm = models.ForeignKey(Recipient_Group, on_delete=models.CASCADE)

    @staticmethod
    def create(user, dm):
        q = CurrentDMUser.objects.filter(user=user, dmid=dm.dmid)
        if q.exists():
            return
        newdmu = CurrentDMUser()
        newdmu.user = user
        newdmu.dmid = dm.dmid
        newdmu.save()

class GroupChat(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    
class Review(models.Model):
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='given_reviews')
    reviewed = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_reviews')
    overall = models.IntegerField(null=False, default=5)
    effective = models.IntegerField(null=False, default=5)
    timeliness = models.IntegerField(null=False, default=5)
    patience = models.IntegerField(null=False, default=5)
    knowledge = models.IntegerField(null=False, default=5)
    created_at = models.DateTimeField(auto_now_add=True)

class Meeting(models.Model):
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    time = models.DateTimeField(auto_now_add=False)
    duration_hours = models.IntegerField(default=0)
    duration_minutes = models.IntegerField(default=0)
    location = models.CharField(max_length=100)
    description = models.CharField(max_length=400)

    def has_passed(self):
        return self.meet_time < datetime.datetime.now()

    def date_orderable_string(self):
        epoch = timezone.make_aware(datetime.datetime.utcfromtimestamp(0))
        return int((self.time - epoch).total_seconds())

main/forms.py
from django import forms
from django.core.validators import EmailValidator, RegexValidator, ValidationError, MinLengthValidator
import re
from .models import *
from .misc_utils import *

class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=50)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        if not User.objects.filter(username__iexact=username).exists():
            raise ValidationError(f"User {username} does not exist.")
        return username


class AccountForm(forms.Form):
    firstname = forms.CharField(label="First Name", max_length=50, validators=[RegexValidator(regex="^[a-zA-Z \-]+$", message="Enter a valid first name")])
    lastname = forms.CharField(label="Last Name", max_length=50, validators=[RegexValidator(regex="^[a-zA-Z \-]+$", message="Enter a valid last name")])
    username = forms.CharField(label="Username", max_length=50)
    email = forms.EmailField(label="Email", max_length=100)
    password = forms.CharField(label="Password", validators=[RegexValidator(regex="^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$", message="Password must be at least 8 characters and contain at least 1 letter and one number")], widget=forms.PasswordInput)
    confirm_password = forms.CharField(label="Confirm Password", validators=[], widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError("User with this email address already exists")
        valid_domains = University.get_valid_domains()
        for domain in valid_domains:
            if email.endswith(domain):
                return email
        raise ValidationError("The email address you provide must be associated with a university")

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username__iexact=username).exists():
            raise ValidationError("Username already in use")
        if not username or not re.match("^[a-zA-Z0-9\-_]+$", username):
            raise ValidationError("Username must contain only letters, numbers, underscores, and dashes")
        if not re.match("^.*[a-zA-Z].*$", username):
            raise ValidationError("Username must contain at least one letter")
        if len(username) > 50:
            raise ValidationError("Username must be less than or equal to 50 characters")
        return username

    def clean(self):
        cleaned_data = super(AccountForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise ValidationError("Passwords don't match")
        return cleaned_data

class StudyGroupForm(forms.Form):
    group_name = forms.CharField(label="Study Group Name", max_length=50, validators=[RegexValidator(regex="^\S.{4,}$", message="Group name must be at least 5 characters")])
    subject = forms.CharField(label="Subject", max_length=50, validators=[RegexValidator(regex="^\S.*$", message="Subject must not be blank")])
    course = forms.CharField(label="Course Prefix and Number (optional)", required=False, validators=[RegexValidator(regex="^[A-Za-z_]{2,3} \d{1,5}$", message="Invalid course prefix and number")])
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={"rows": "5"}))

class GroupPostForm(forms.Form):
    title = forms.CharField(label="Title", max_length=130, validators=[RegexValidator(regex="^\S.*$", message="Title must not be blank")])
    image_source = forms.CharField(label="Image Source (Optional)", required=False, max_length=1000)
    text = forms.CharField(label="Post Text", required=False, widget=forms.Textarea(attrs={"rows": "5"}))

    def clean_image_source(self):
        image_source = self.cleaned_data["image_source"]
        if image_source and not is_url_image(image_source):
            raise ValidationError("Link does not point to image")
        return image_source

    def clean(self):
        cleaned_data = super(GroupPostForm, self).clean()
        image_source = cleaned_data.get("image_source")
        text = cleaned_data.get("text")
        if not text and not image_source:
            raise ValidationError("Post must contain image or text")
        return cleaned_data

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/favicon.ico' %}" >
    <link href="{% static 'main/style.css' %}" rel="stylesheet" type="text/css" />
    <title>{% block title %}{% endblock title %}</title>

  </head>
  <body>
  {% if request.user.is_authenticated %}
  <nav class="navbar">
    <ul>
      <li style="margin-left: 30px; margin-right: 20px;"><div style="margin-top: 7px;"><img src="{% static 'main/UtorLogoNavBar.png' %}" width=80px /></div></li>
      <li><a href="{% url 'index' %}">Home</a></li>
      <li><a href="{% url 'study_groups' %}">Study Groups</a></li>
      <li><a href="{% url 'tutor_search' %}">Find a Tutor</a></li>
      <li><a href="{% url 'message_page' %}">Messages</a></li>
      <li style="float: right; margin-right: 20px;"><a href="{% url 'logout' %}">Logout</a></li>
      <li style="float: right;"><a href="{% url 'profile' request.user.username %}">My Profile</a></li>
      <li style="float: right;"><a href="{% url 'notifications' %}">
                                                                        {% if request.user.has_notifications %}
                                                                        <span id="notification_dot"><img width=10px src="{% static 'main/red_dot.png' %}"/></span>
                                                                        {% endif %}
                                                                        Notifications
                                                                        <span style="display: none;" id="num_notifications">{{ request.user.num_notifications }}</span>
                                                                                  </a></li>
    </ul>
  </nav>
  {% else %}
  <nav class="navbar">
    <ul>
      <li style="margin-left: 30px; margin-right: 20px;"><div style="margin-top: 7px; margin-bottom: 3px;"><img src="{% static 'main/UtorLogoNavBar.png' %}" width=80px /></div></li>
    </ul>
  </nav>
  {% endif %}
  {% block content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  {% endblock content %}
  {% block script %}{% endblock script %}
  </body>
</html>

main/templates/create_study_group.html
{% extends 'base.html' %}

{% block title %}Create a Study Group{% endblock %}

{% block content %}
<div class="outer">
  <div class="form">
    <div>
      <a class="anchorbutton" href="{% url 'study_groups' %}">Back</a>
    </div>
    <div class="center text-center">
      <h2>Create a Study Group</h2>
    </div>
    <form class="form" action="{% url 'create_study_group' %}" method="POST">
      {% csrf_token %}
      <table class="form-table">
      {% for field in form %}
        <tr>
          <th valign="top" style="text-align:left;">{{ field.label }}</th>
          <td class="fullwidth-text-input">{{ field }}</td>
          <td>
            {%for error in field.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </td>
        </tr>
      {% endfor %}
      </table>
      <div class="center text-center">
        <input type="submit" value="Submit" />
      </div>
    </form>
  </div>
</div>
{% endblock %}

main/templates/group_chat.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ group.name }} Group Chat{% endblock %}

{% block content %}
<div class="outer">
  <div class="maindiv">
    <div class="center">
      <a style="float: left;" class="anchorbutton" href="{% url 'view_group' group.id %}">Back</a>
      <h3 style="text-align: center;">{{ group.name }} Group Chat</h3>
    </div>

    <div class="sidebyside" style="background: #9BD; width: 95%;">
      <div class="groupchatouter" style="width: 80%;">
        <div class="groupchatbox" id="groupchatbox">
          {% for chat in group.groupchat_set.all %}
            <div class="chatbox">
              <div class="flexrow center">
                <div style="width: 82%;">
                  <h4 class="nomargin" style="width: 80%;"><a href="{% url 'profile' chat.sender.username %}" class="userlink">{{ chat.sender.username }}</a></h4>
                </div>
                <div style="text-align: right; font-size: 11px; color: gray; margin-right: 10px; margin-top: 4px;">{{ chat.time|date:"n/j/y g:i" }}&nbsp;{{ chat.time|date:"A" }}</div>
              </div>
              <p>{{ chat.message }}</p>
              <hr/>
            </div>
          {% endfor %}
        </div>
        <div class="flexrow">
          <textarea type="text" id="chatinput" rows="3" style="width: 90%;"></textarea><button style="width: 10%;" onclick="sendMessage();">Send</button>
        </div>
      </div>
      <div class="chatusersdisplay" style="width: 20%;" id="chatusersdisplay">
        {% for usr in group.currentgroupchatuser_set.all %}
          <div id="user{{ usr.user.id }}"><a class="userlink" href="{% url 'profile' usr.user.username %}">{{ usr.user.username }}</a><hr/></div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'main/group_chat.js' %}"
                          defer
                          data-groupid="{{ group.id }}"
                          data-groupname="{{ group.name }}"></script>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="outer">
	<div class="maindiv" style="background-image: linear-gradient(0deg, #AABBCC, #DDF);">
		<div class="flexrow">
			<div style="border: 1px solid #AABBCC; width: 30%;">
				<div style="padding: 2.5%; width: 95%;">
					<h3>Privacy Policy</h3>
					<h5>What Data Utor Collects</h5>
					<p>Utor collects your name, zip code, university email, and subjects that you enter
					into your profile. We also collect and save all messages and posts our
					users make. We will not collect you exact location or any financial
					information.</p>
					<p>Any payment agreements with tutors should be handled outside of the Utor
					website.</p>
					<h5>Why We Collect This Data</h5>
					<p>Any data we collect is intended to improve your experience on our site (for
					example we collect your zip code to help connect you with tutors in your
					area, and we collect university emails to verify our users to improve the
					safety of our site. We collect and save interactions on our site to protect
					our users from harassment.</p>
					<h5>Your Rights to Your Data</h5>
					<p>We want all of our users to be able to exercise control over the data we collect.
					If you want data specific to you removed and deleted please contact us at our
					support email: utor.service@gmail.com with your username and details on what
					you want removed. If a user has violated US Law in any way we will turn
					over any and all relevant data to authorities (ex. threats made over our
					site, solicitation of illegal services).</p>
				</div>
			</div>
			<div style="border: 1px solid #AABBCC; width: 40%;">
				<div class="center text-center">
					<h1>Welcome to Utor!</h1>
					<hr/>
					<img src="{% static 'main/UtorLogo.png' %}" style="width: 70%; margin-top: 20px;"/>
				</div>
				<div style="padding: 2.5%; width: 95%;">
					<h3>Mission Statement</h3>
					<p style="text-align: left;">Utor aims to increase academic achievement among college students by helping them to get academic help in the form of study groups and tutors.  Further, Utor aims to make the process of finding this help easy and efficient.</p>
				</div>
			</div>
			<div style="border: 1px solid #AABBCC; width: 30%;">
				<div style="padding: 2.5%; width: 95%;">
					<h3>Terms of Service</h3>
					<h5>Safety Policy</h5>
					<p>If you experience harassment in any form please contact our email:
					utor.service@gmail.com with your username and a description of the issue.</p>
					<p>We will review the issue and take appropriate actions (see <em>Violating Utor’s Terms
					of Service</em>).</p>
					<h5>Honesty Policy</h5>
					<p>Users are expected to be forthright and honest about what they are capable of
					tutoring. Users who are reported as not knowing any relevant subject
					matter in regards to what they claim to be able to tutor will be
					reviewed by Utor’s team. If tutors on the site are in fact incapable of
					tutoring they will be found in violation of our terms of service (see
					<em>Violating Utor’s Terms of Service</em>).</p>
					<h5>Violating Utor’s Terms of Service</h5>
					<p>If we receive a complaint about a user account and determine that our policy
					has been violated, the user in question will be removed from our site
					immediately. In the event that another user’s safety was
					threatened or a crime was committed we will turn over any relevant
					evidence to authorities in an effort to protect our
					users.</p>
				</div>
			</div>
		</div>
		<div class="center">
			<div style="padding-left: 20px; padding-right: 20px;">
				<h5>Credits</h5>
				<p>Utor is a website created by Ben Lenox and Michael Sciole.</p>

				<p>Utor uses the following libraries and services:
					<a href="https://www.djangoproject.com/">Django</a>,
					<a href="https://github.com/django/daphne">Daphne</a>,
					<a href="https://github.com/django/channels">Channels</a>,
					<a href="https://github.com/evansd/whitenoise">Whitenoise</a>,
					and <a href="https://www.zipwise.com/">ZipWise</a>.
				</p>

				<p>In addition, Utor makes use of a
					<a href="https://github.com/Hipo/university-domains-list">database containing university domains<a>
						 available under the MIT license,
			and <a href="https://gist.github.com/straker/ff00b4b49669ad3dec890306d348adc4#file-readme-md">
						code written by Steven Lambert</a>
						 available under the CC0 1.0 Universal License.</p>


			</div>
		</div>
	</div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="outer">
  <div class="form smallform">
    <div class="text-center center">
      <img src="{% static 'main/UtorLogo.png' %}" width=150px />
    </div>
    <div class="center text-center">
      <h2>Login</h2>
    </div>
    {% if message %}
    <div class="alert-message">
      {{ message }}
    </div>
    {% elif form.username.errors %}
    <div class="alert-message">
      {{ form.username.errors.0 }}
    </div>
    {% endif %}
    <form class="form-form" action="{% url 'login' %}" method="POST">
      {% csrf_token %}
      <table class="form-table">
      {% for field in form %}
        <tr>
          <th style="text-align:left;">{{ field.label }}</th>
          <td>{{ field }}</td>
        </tr>
      {% endfor %}
      </table>
    <div class="center text-center">
      <input type="submit" value="Submit" class="anchorbutton"/>
    </div>
    </form>
    <div>
      <a class="anchorbutton" href="{% url 'create_account' %}">Create Account</a>
    </div>
  </div>
<div>
{% endblock %}

main/templates/make_post.html
{% extends 'base.html' %}

{% block title %}Post to {{ group.name }}{% endblock %}

{% block content %}
<div class="outer">
  <div class="form">
    <div>
      <a class="anchorbutton" href="{% url 'view_group' group.id %}">Back</a>
    </div>
    <div class="center text-center">
      <h2>Post to {{ group.name }}</h2>
    </div>
    <form class="form" action="{% url 'make_post' group.id %}" method="POST">
      {% csrf_token %}
      <table class="form-table">
      {% for field in form %}
        <tr>
          <th valign="top" style="text-align:left;">{{ field.label }}</th>
          <td class="fullwidth-text-input">{{ field }}</td>
          <td>
            {%for error in field.errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </td>
        </tr>
      {% endfor %}
      {% if form.non_field_errors %}
      <tr>
        {%for error in form.non_field_errors %}
          <td class="text-center" colspan="3">{{ error }}</td>
        {% endfor %}
      </tr>
      {% endif %}
      </table>
      <div class="center text-center">
        <input type="submit" value="Submit" />
      </div>
    </form>
  </div>
</div>
{% endblock %}